version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: continuumio/miniconda3
    working_directory: ~/repo
    steps:
      - checkout
      - python/load-cache
      - run:
          name: install dependencies
          shell: /bin/bash
          command: |
            /bin/bash
            conda init bash
            conda env create -f conda_environment_docker.yml
            conda activate maximizer
      - python/save-cache
      - run:
          command: pytest
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
