version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: continuumio/miniconda3
    working_directory: ~/repo
    steps:
      - checkout
      - python/load-cache
      - run:
          name: install dependencies
          shell: /bin/bash
          command: |
            conda init bash
            source /root/.bashrc
            conda env create -f conda_environment_docker.yml
      - python/save-cache
      - run:
          name: Test
          shell: /bin/bash
          command: |
            conda init bash
            source /root/.bashrc
            conda activate maximizer
            pytest

workflows:
  main:
    jobs:
      - build-and-test
